"""update product table to include cart_img_url

Revision ID: 5056344cb179
Revises: 48980ae98cf1
Create Date: 2022-12-18 16:01:01.137001

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '5056344cb179'
down_revision = '48980ae98cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cart_img_url', sa.String(length=1000), nullable=True))

    # if environment == "production":
    #     op.execute(f"ALTER TABLE products SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cart_img_url')
    # ### end Alembic commands ###
